theme: minima
title: "Пуэрто Рико на таблицах"
description: "Моделирование логики настольной игры 'Пуэрто Рико' с помощью таблиц принятия решений"
author: "Евгений Терехов"
github_username: nergal-perm
linkedin_username: eterehov-java-lead
youtube_username: "@EugeneWritesCode"
rss: rss
