theme: minima
title: "Пуэрто Рико на таблицах"
description: "Моделирование логики настольной игры 'Пуэрто Рико' с помощью таблиц принятия решений"
author: 
  name: "Евгений Терехов"
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nergal-perm" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/eterehov-java-lead/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@EugeneWritesCode" }
    - { platform: telegram, user_url: "https://t.me/evgen_voheret" }
