locators:
  - table
  - undefined
  - player1
  - player2
  - player3
  - player4
  - player5
  - turnOrder
  - board
  - phase
  - temp
  - plantation0
  - plantation1
  - plantation2
  - plantation3
  - plantation4
  - plantation5
  - plantation6
  - plantation7
  - plantation8
  - plantation9
  - plantation10
  - plantation11
  - plantation12
  - plantation13
  - plantation14
  - plantation15
  - plantation16
  - plantation17
  - plantation18
  - plantation19
  - plantation20
  - plantation21
  - plantation22
  - plantation23
  - plantation24
  - plantation25
  - plantation26
  - plantation27
  - plantation28
  - plantation29
  - plantation30
  - plantation31
  - plantation32
  - plantation33
  - plantation34
  - plantation35
  - plantation36
  - plantation37
  - plantation38
  - plantation39
  - plantation40
  - plantation41
  - plantation42
  - plantation43
  - plantation44
  - plantation45
  - plantation46
  - plantation47
  - plantation48
  - plantation49
  - plantation50
  - taken
  - quarry1
  - quarry2
  - quarry3
  - quarry4
  - quarry5
  - quarry6
  - quarry7
  - quarry8
